language: java
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "hQSPkKY9Lta8xcDjvv6xiU2DDOpvLuCwHgkRn5NxmCJSyPRononbJm4hiTtz7Af+6Nkqk7sSWGW9ZRFt0BJ9FvT8r+OlN+ITl7dZdXoqubXoKVgExtBRHLZHT33D4tXP3FB9t6U4uET3qZv9dRB+3K2OqtuGx1UnHXnj+I5We3t5g7uriW/AAzIMzrcglWAGCtzRsLp+HWQZuWc3w01LS3FDDPj0hskkdp8eVmk0FHnKu0lScFB1mph99aS1VRlSx/UesAp7MTxOgSMufA1jE/610Oei8gVpsgoUZNHsrYH1xwrjgwnDMNCnVlgPFLtfWvWrXoj380cb1OV9b/wLybbbmjxcFqi5oSzb5Da+iy1YZVKSAnFkvkanDtocE/iMNatEPHSZbUi1PGJeNVqz+VNqX7KZtTReInZ3LraWCstIi3koxBKkSn5sZwHX6RXaU2Rla72jgyLjv52sFWhUZHYN9fKbAiHtw8fkPQj2eAqwscRaEI1EbXv1Ar3JBUegRz3FfH4hvRP1Zh14tVUe+NOXYNqI8UkHzFEdcKOnUK4rHaa6Oqfyxo9OA0NdgCGc0P9YUOEnzRdEbfhaMBQ2x59XCcQrgkBJT4wEW8NIJnn3h0AFOJdjTNNYcinImph0sVMKfS0UNM98o/d0tgykpfxVtVa1XyiBMAoYRit6Zlo="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "BujakiAttila/MapIT"
      description: "Build submitted via Travis CI"
    notification_email: bujaki.attila@gmail.com
    build_command_prepend: "gradlew clean"
    build_command:   "gradlew build"
    branch_pattern: coverity_scan